# Config file for Air (https://github.com/air-verse/air) in TOML format
root = "."
tmp_dir = "tmp"

[build]
# Run CSS build and templ generate before building Go code
pre_cmd = ["tailwindcss -i ./assets/css/input.css -o ./assets/css/tailwind.css --minify", "templ generate"]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "APP_ENV=development ./tmp/main server"
include_ext = ["go", "templ", "css"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules", "bin", "api", "lexicons", "internal/pds"]
exclude_file = ["components/components_templ.go"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 500
stop_on_error = true
send_interrupt = false
kill_delay = 500
rerun = false
rerun_delay = 500

[log]
time = true
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = false
# proxy_port = 8090
# app_port = 8080
