version: "2"

run:
  timeout: 5m
  go: "1.23"

linters:
  default: standard
  enable:
    - gocritic
    - revive
    - gosec
    - unconvert
    - unparam
    - misspell
    - prealloc
    - nolintlint