version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: disquest-postgres
    environment:
      POSTGRES_DB: disquest
      POSTGRES_USER: disquest
      POSTGRES_PASSWORD: disquest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U disquest -d disquest"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: