# fly.toml app configuration file generated for dis-quest-cold-pond-8708 on 2025-05-31T23:46:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dis-quest'
primary_region = 'atl'

[build]

[env]
  APP_ENV = 'production'
  # Set environment variables here
  # For example, to set a variable named "FOO" to "bar", uncomment the line below:
  # FOO = 'bar'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# [[http_service.machine_checks]]
#   image = "curlimages/curl"
#   entrypoint = ["/bin/sh", "-c"]
#   command = ["curl http://[$FLY_TEST_MACHINE_IP] | grep 'OK'"]
#   kill_signal = "SIGKILL"
#   kill_timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
