version: '3'

tasks:
  run:
    cmds:
      - go run . start
    silent: true

  build:
    cmds:
      - templ generate
      - sqlc generate
      - go build -o bin/disquest ./

  docker:
    cmds:
      - docker build .

  watch:
    cmds:
      - templ generate
      - reflex -r '\.go$|\.templ$' -s -- sh -c 'go run . start'
    silent: true

  test:
    cmds:
      - go test ./...

  dev:
    cmds:
      - air
    silent: false

  # Database commands
  db-migrate:
    desc: Run database migrations
    cmds:
      - tern migrate

  db-rollback:
    desc: Rollback last database migration
    cmds:
      - tern migrate --destination -1

  db-reset:
    desc: Reset database to clean state
    cmds:
      - tern migrate --destination 0
      - tern migrate

  db-status:
    desc: Show database migration status
    cmds:
      - tern status

  generate:
    desc: Generate all code (templ + sqlc)
    cmds:
      - templ generate
      - sqlc generate

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run
