version: '3'

tasks:
  run:
    cmds:
      - go run . start
    silent: true

  build:
    cmds:
      - templ generate
      - go build -o bin/disquest ./

  docker:
    cmds:
      - docker build .

  watch:
    cmds:
      - templ generate
      - reflex -r '\.go$|\.templ$' -s -- sh -c 'go run . start'
    silent: true

  test:
    cmds:
      - go test ./...

  dev:
    cmds:
      - air
    silent: false
