// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Message struct {
	Did               string         `json:"did"`
	Rkey              string         `json:"rkey"`
	TopicDid          string         `json:"topic_did"`
	TopicRkey         string         `json:"topic_rkey"`
	ParentMessageRkey sql.NullString `json:"parent_message_rkey"`
	Content           string         `json:"content"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type Participation struct {
	Did       string    `json:"did"`
	TopicDid  string    `json:"topic_did"`
	TopicRkey string    `json:"topic_rkey"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Topic struct {
	Did            string         `json:"did"`
	Rkey           string         `json:"rkey"`
	Subject        string         `json:"subject"`
	InitialMessage string         `json:"initial_message"`
	Category       sql.NullString `json:"category"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	SelectedAnswer sql.NullString `json:"selected_answer"`
}
