// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	// Messages queries
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// Participation queries
	CreateParticipation(ctx context.Context, arg CreateParticipationParams) (Participation, error)
	// queries.sql - Central SQL query file for dis.quest
	// All SQL queries should be added to this file as documented in CLAUDE.md
	// Topics queries
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteParticipation(ctx context.Context, arg DeleteParticipationParams) error
	DeleteTopic(ctx context.Context, arg DeleteTopicParams) error
	GetMessage(ctx context.Context, arg GetMessageParams) (Message, error)
	GetMessagesByTopic(ctx context.Context, arg GetMessagesByTopicParams) ([]Message, error)
	GetParticipation(ctx context.Context, arg GetParticipationParams) (Participation, error)
	GetParticipationsByTopic(ctx context.Context, arg GetParticipationsByTopicParams) ([]Participation, error)
	GetParticipationsByUser(ctx context.Context, did string) ([]Participation, error)
	GetRepliesByMessage(ctx context.Context, arg GetRepliesByMessageParams) ([]Message, error)
	GetTopic(ctx context.Context, arg GetTopicParams) (Topic, error)
	GetTopicsByCategory(ctx context.Context, arg GetTopicsByCategoryParams) ([]Topic, error)
	GetTopicsByDID(ctx context.Context, did string) ([]Topic, error)
	ListTopics(ctx context.Context, arg ListTopicsParams) ([]Topic, error)
	UpdateParticipationStatus(ctx context.Context, arg UpdateParticipationStatusParams) error
	UpdateTopicSelectedAnswer(ctx context.Context, arg UpdateTopicSelectedAnswerParams) error
}

var _ Querier = (*Queries)(nil)
