name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: Build
        run: go build -v ./...
      - name: Run tests
        run: go test -v ./...
