name: Conventional Commits

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  conventional-commits:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commit messages
        run: |
          # Simple conventional commit validation without scopes
          # Format: type: description
          # Types: feat, fix, chore, docs, style, refactor, test, perf, ci, build, revert
          
          commit_regex='^(feat|fix|chore|docs|style|refactor|test|perf|ci|build|revert): .{1,50}'
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # For PRs, check all commits in the PR
            commits=$(git rev-list --no-merges ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          else
            # For direct pushes to main, check the latest commit
            commits=$(git rev-parse HEAD)
          fi
          
          echo "Validating commits..."
          invalid_commits=0
          
          for commit in $commits; do
            message=$(git log --format=%s -n 1 $commit)
            echo "Checking commit: $commit"
            echo "Message: $message"
            
            if ! echo "$message" | grep -qE "$commit_regex"; then
              echo "❌ Invalid commit message format: $message"
              echo "Expected format: type: description"
              echo "Valid types: feat, fix, chore, docs, style, refactor, test, perf, ci, build, revert"
              echo "Examples:"
              echo "  feat: add user authentication"
              echo "  fix: resolve database connection issue"
              echo "  chore: update dependencies"
              invalid_commits=$((invalid_commits + 1))
            else
              echo "✅ Valid commit message"
            fi
            echo ""
          done
          
          if [ $invalid_commits -gt 0 ]; then
            echo "❌ Found $invalid_commits invalid commit message(s)"
            exit 1
          else
            echo "✅ All commit messages follow conventional commit format"
          fi